version: "3"
services:
  web:
    image: nginx:1.12-alpine
    volumes:
      - public_html:/usr/share/nginx/html
    restart: always
    ports: # host:container
      - "${HTTP_PORT}:80"
  weewx:
    image: mitct02/weewx:3.7.1
    volumes:
      - public_html:/home/weewx/public_html
volumes:
  public_html:
