version: "3"
services:
  web:
    image: nginx:1.12-alpine
    volumes:
      - public_html:/usr/share/nginx/html
    restart: always
    ports: # host:container
      - "80:80"
  weewx:
    environment:
      - CONF=dev
    image: mitct02/weewx:3.8.0
    volumes:
    # public_html - shared with web service - def is in volumes: below
      - public_html:/home/weewx/public_html
    # another option: local directory, so the db doesnt start from scratch
      - /Users/tom/tmp/weewx/archive:/home/weewx/archive
    restart: always
volumes:
  public_html:
